#!/usr/bin/env zsh

## If alacritty.yml does not exist, raise an alert
[[ ! -f ~/.config/alacritty/alacritty.yml ]] && \
    notify-send "alacritty.yml does not exist" && exit 0

## Fetch background_opacity from alacritty.yml
opacity=$(awk '$1 == "opacity:" {print $2; exit}' \
    ~/.config/alacritty/alacritty.yml)

## Assign toggle opacity value
new_opacity=1
case $1 in
    "dec")
        new_opacity=$(echo "$opacity-$2" | bc)
        if (( $(echo "$new_opacity < 0") | bc -l )); then
            new_opacity=0
        fi
    ;;
    "inc")
        new_opacity=$(bc <<< "$opacity+$2")
        if (( $(echo "$new_opacity > 1") | bc -l )); then
            new_opacity=1
        fi
    ;;
esac
echo $new_opacity
## Replace opacity value in alacritty.yml
sed -i -- "s/opacity: $opacity/opacity: $new_opacity/" \
    ~/.config/alacritty/alacritty.yml
