#!/usr/bin/env python3

from argparse import ArgumentParser
from os import path, makedirs
from shutil import copy, copy2

cache_path = path.expanduser('~/.cache/tools/fileswitch.temp')


def parser_create() -> ArgumentParser:
    parser = ArgumentParser(description='Swap files.')
    parser.add_argument('paths', type=str, nargs='+',
                        help='Pathes destinations.')
    parser.add_argument('-m', '--metadata', dest='metadata',
                        action='store_true',
                        help='Attempts to preserve files metadata.')
    return parser


def pathsValidate(paths) -> None:
    for p in paths:
        if not path.exists(p):
            raise FileExistsError


def dataValidate(args) -> None:
    paths = args.paths
    if len(args.paths) != 2:
        raise Exception("Need 2 pathes.")
    pathsValidate(paths)


def create_path(filename) -> None:
    if not path.exists(path.dirname(filename)):
        try:
            makedirs(path.dirname(filename))
        except OSError as exc:
            raise exc


def switch_files(path1, path2) -> None:
    copy(path1, cache_path)
    copy(path2, path1)
    copy(cache_path, path2)


def switch_files_with_metadata(path1, path2) -> None:
    copy2(path1, cache_path)
    copy2(path2, path1)
    copy2(cache_path, path2)


def main():
    parser = parser_create()
    args = parser.parse_args()
    dataValidate(args)
    path1, path2 = args.paths
    create_path(cache_path)
    if args.metadata:
        switch_files_with_metadata(path1, path2)
    else:
        switch_files(path1, path2)


if __name__ == "__main__":
    main()
