#!/usr/bin/env python3.8

from argparse import ArgumentParser, RawTextHelpFormatter
import subprocess
import textwrap
from os.path import exists


def parser_create() -> ArgumentParser:
    parser = ArgumentParser(
        description="Run python virtualenv environment",
        prog="Virtual Environment Runner",
        formatter_class=RawTextHelpFormatter,
        epilog=textwrap.dedent(
            """\
                    Dependencies:
                      virtualenv - version 20+
                """
        ),
    )
    parser.add_argument(
        "-p",
        "--python",
        dest="python",
        nargs="?",
        type=str,
        default="3.8",
        help="Specify python version",
    )

    parser.add_argument(
        "-e",
        "--envname",
        dest="envname",
        nargs="?",
        type=str,
        default="venv",
        help="Specify environment name",
    )
    return parser


def envExist(foldername="venv") -> bool:
    if not exists(foldername):
        return False
    return True


def make_command(cmd: str, envname: str, python_version: str) -> list:
    command = f"{cmd} {envname} -p {python_version}".split()
    return command


def start():
    parser = parser_create()
    args = parser.parse_args()

    cmd_start = make_command("virtualenv", args.envname, args.python)

    if not envExist(args.envname):
        subprocess.run(cmd_start)


if __name__ == "__main__":
    start()
